# Generated by Django 5.2.10 on 2026-03-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publickey",
            name="encrypted_private_key",
            field=models.TextField(
                blank=True,
                help_text="User's RSA Private Key encrypted with their password",
                null=True,
            ),
        ),
    ]
