# Generated by Django 5.2.10 on 2026-03-08 00:43

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Ya existe un usuario con ese nombre."},
                help_text="Requerido. 150 caracteres o menos. Letras, dígitos, espacios y @/./+/-/_ permitidos.",
                max_length=150,
                unique=True,
                validators=[apps.users.models.AllowedSpacesUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
