# Generated by Django 5.2.10 on 2026-03-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_group_and_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='encrypted_symmetric_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
