# Generated by Django 5.2.10 on 2026-03-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_groupmember_encrypted_symmetric_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="server_encrypted_aes_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
